name: Reply to issue

on:
  issues:
    types: [opened]

jobs:
  replyToIssue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print issue data
        run: |
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          
      - name: Run Inference
        id: inferenceOutput
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://zfb2nt2z77.execute-api.us-west-2.amazonaws.com/test/issue-similarity-inference'
          method: 'POST'
          data: '{"data": ["${{ github.event.issue.title}}"]

      - name: Reply to issue
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.inferenceOutput.outputs.response }}
