name: Reply to issue

on:
  issues:
    types: [opened]

jobs:
  replyToIssue:
    runs-on: ubuntu-latest

    steps:
      - name: Run Inference
        id: inferenceOutput
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://90tohuxjy0.execute-api.us-west-2.amazonaws.com/v1/amplify-github-issue-similarity'
          method: 'POST'
          data: '{"data": "${{ github.event.issue.title}}"}'
          timeout: 30000
          
      - name: Remove quotes
        id: removeQuotes
        run: |
          body=${ ${{steps.inferenceOutput.outputs.response}}:1:-1}

      - name: Reply to issue
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.removeQuotes.body }}
